import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

type Language = 'zh' | 'en';

interface Translations {
  [key: string]: string | Translations;
}

const translations: Record<Language, Translations> = {
  zh: {
    // Common
    appName: 'IBC 排班系统',
    selectUser: '选择用户',
    addUser: '新增用户',
    backToHome: '返回首页',
    submit: '提交',
    cancel: '取消',
    confirm: '确认',
    delete: '删除',
    edit: '编辑',
    save: '保存',
    loading: '加载中...',
    time: '节次',
    slots: '时段',
    
    // Home Page
    welcome: '请选择你的名字',
    welcomeSubtitle: '选择你的名字以开始排班',
    homeWeeklyScheduleTitle: '本周班表',
    homeWeeklyScheduleSubtitle: '展开查看当前整周排班安排，首页只读展示。',
    homeWeeklyScheduleEmpty: '本周暂未安排班表',
    homeWeeklyScheduleExpand: '点击展开查看本周班表',
    homeWeeklyScheduleCollapse: '点击收起本周班表',
    homeWeeklyScheduleAssignedCount: '已排班时段',
    homeWeeklyScheduleParticipants: '参与人数',
    enterName: '输入姓名',
    adminLogin: '管理员登录',
    
    // Schedule Page
    scheduleTitle: '排班表',
    scheduleSubtitle: '请点击格子标记可排班时段',
    selectedSlots: '已选时段',
    available: '可排班',
    unavailable: '不可排班',
    morning: '上午',
    afternoon: '下午',
    info: '点击格子即可标记你的可排班时段。蓝色表示已选择。',
    
    // Admin
    adminTitle: '管理员登录',
    adminSubtitle: '请输入管理员密码',
    enterPassword: '输入密码',
    login: '登录',
    logout: '登出',
    wrongPassword: '密码错误',
    loggedIn: '已登录',
    collapseSidebar: '收起侧边栏',
    expandSidebar: '展开侧边栏',
    scheduleHistory: '排班记录',
    scheduleHistorySubtitle: '查看最近五次排班记录并回溯详情',
    subsidyRecords: '补贴记录',
    subsidyRecordsSubtitle: '管理已导出的补贴明细，支持查看、复制、再次导出与继续编辑。',
    subsidyRecordsEmpty: '暂无已导出的补贴记录',
    historyRange: '排班范围',
    historyParticipants: '参与助理',
    historyGeneratedAt: '生成时间',
    historyGenerationMode: '生成方式',
    historyCreatedBy: '创建人',
    historyViewDetails: '查看详情',
    historyEmpty: '暂无排班记录',
    historyViewing: '历史排班详情',
    historyBackToLive: '返回当前排班',
    autoGenerated: '自动',
    manualGenerated: '手动',
    
    // Admin Tabs
    scheduleOverview: '排班总览',
    userManagement: '用户管理',
    
    // Admin Schedule
    viewSchedule: '查看和管理所有排班',
    clearSchedule: '清除',
    autoSchedule: '自动排班',
    exportWord: '导出 Word',
    exportCSV: '导出 CSV',
    exportSubsidy: '导出补贴明细',
    periodDay: '节次 / 星期',
    unassigned: '未安排',
    totalUsers: '总用户数',
    scheduledSlots: '已排班时段',
    totalAvailable: '总可用时段',
    
    // Admin Users
    addNewUser: '新增用户',
    allUsers: '所有用户',
    noUsers: '暂无用户',
    noPhone: '未设置',
    editUserProfile: '编辑人员资料',
    phoneNumber: '手机号',
    studentId: '学号',
    department: '院系',
    major: '专业',
    studentType: '本科生/研究生',
    grade: '年级',
    enterStudentId: '输入学号',
    enterDepartment: '输入院系',
    enterMajor: '输入专业',
    enterStudentType: '例如：本科',
    enterGrade: '例如：2023',
    subsidyProfileReady: '补贴资料已补全',
    subsidyProfileIncomplete: '补贴资料待补全',
    profileSyncRemoteSaved: '补贴资料已保存到云端。',
    profileSyncLocalOnly: '本机已暂存，云端未保存，请修复后重试。',
    subsidySchemaWarning: '补贴资料表结构异常，当前云端读写可能不可用。',
    subsidySchemaBlocked: '补贴资料表缺少必要字段，已阻断云端保存与补贴导出。',
    exportSubsidyTitle: '导出补贴明细表',
    exportSubsidySubtitle: '导出本月自然月的补贴明细，格式保持与模板一致。',
    subsidyDraftActive: '当前为云端草稿',
    subsidyDraftNew: '当前为新建编辑态',
    subsidyDraftLoading: '正在加载草稿...',
    subsidyDraftLoaded: '已自动续上你上次保存的草稿。',
    subsidyDraftLoadFailed: '草稿加载失败，已改为使用当前排班生成新编辑态。',
    subsidyDraftSaved: '草稿已保存到云端。',
    subsidyDraftSaveFailed: '保存草稿失败，请稍后重试。',
    subsidyExportArchived: '补贴明细已导出并归档。',
    subsidyExportFailed: '补贴明细导出失败，请稍后重试。',
    saveDraft: '保存草稿',
    exportAndArchive: '导出并归档',
    preparerName: '制表人签字',
    preparerPhone: '制表人电话',
    preparedDate: '制表日期',
    naturalMonthRange: '统计区间',
    hourlyRate: '时薪',
    monthlyHours: '本月工时',
    systemHours: '系统工时',
    approvedHours: '核定工时',
    subsidyAmount: '应发金额',
    totalsLabel: '合计',
    totalApprovedHours: '总工时',
    totalApprovedAmount: '总金额',
    overLimitNote: '超 711 元备注',
    exportNow: '立即导出',
    missingProfileData: '以下人员仍缺少补贴资料，请先补全：',
    noScheduledUsers: '本月没有可导出的排班资料',
    exportListEmpty: '当前导出列表为空，请先添加助理或保留至少一条记录',
    allowanceReady: '可导出',
    allowanceNeedsNote: '需备注',
    allowanceMissingData: '缺资料',
    assistantName: '助理姓名',
    addAssistant: '添加助理',
    addAssistantSubtitle: '从现有助理名单中补充本次导出需要的助理。',
    searchAssistantPlaceholder: '搜索未在当前列表中的助理',
    noAssistantsToAdd: '没有可添加的助理',
    confirmRemoveAssistant: '移除助理',
    confirmRemoveAssistantMessage: '确定要移除该助理吗？移除后本次导出将不包含此人。',
    subsidyRecordMonth: '补贴月份',
    subsidyRecordExportedAt: '导出时间',
    subsidyRecordDetails: '补贴记录详情',
    subsidyRecordContinueEdit: '继续编辑',
    subsidyRecordCopy: '复制记录',
    subsidyRecordReExport: '再次导出',
    subsidyRecordDelete: '删除记录',
    subsidyRecordCopied: '已复制为新的云端草稿。',
    subsidyRecordReadyToEdit: '已基于该记录创建草稿，可继续编辑。',
    subsidyRecordCloneFailed: '复制记录失败，请稍后重试。',
    subsidyRecordReExported: '已重新导出该补贴记录。',
    subsidyRecordDeleted: '补贴记录已删除。',
    subsidyRecordDeleteFailed: '删除补贴记录失败，请稍后重试。',
    subsidyRecordConfirmDelete: '删除补贴记录',
    subsidyRecordConfirmDeleteMessage: '确定要删除这条已导出的补贴记录吗？删除后无法恢复。',
    subsidySourceSchedule: '排班导出',
    subsidySourceRecordCopy: '记录复制',
    invalidApprovedHours: '请输入有效工时',
    negativeApprovedHours: '工时不能为负数',
    hoursLimitExceeded: '工时不能超过 30 小时',
    hoursUnitShort: 'h',
    selectAssignee: '选择排班人员',
    unassign: '取消排班',
    selected: '已选择',
    noOneAvailable: '暂无人员可排',
    peopleAvailable: '人可选',
    extraDutyPlaceholder: '例如：本月额外值班安排',
    autoScheduleSettingsTitle: '自动排班参数',
    autoScheduleSettingsSubtitle: '调整理论工时上限与工时接近判定，再执行自动排班。',
    weeklySoftLimitHours: '每周理论上限（小时）',
    closeHoursThreshold: '工时接近阈值（小时）',
    explanationInfo: '排班解释',
    assignedResult: '已分配',
    matchedRules: '命中规则',
    candidateList: '候选人',
    rejectionReasonTitle: '未选中原因',
    noExplanation: '该班次暂无解释信息',
    explanation: {
      badge: {
        singleCandidate: '单人锁定',
        hoursPriority: '工时优先',
        continuityPriority: '连续优先',
        stableTiebreak: '稳定平局',
        manualAssignment: '人工分配',
        softLimitWarning: '接近上限',
      },
      rule: {
        singleCandidate: '单人锁定',
        hoursPriority: '工时优先',
        continuityPriority: '连续优先',
        stableTiebreak: '稳定平局',
        manualAssignment: '人工分配',
      },
      reason: {
        softLimitReached: '已接近或超过理论上限',
        higherWeeklyHours: '本周工时更高',
        lowerContinuitySameHours: '工时相同，但连续性较差',
        lowerContinuityCloseHours: '工时接近，但连续性较差',
        stableTiebreak: '稳定平局规则靠后',
      },
      note: {
        softLimitWarning: '已接近或超过理论上限',
        manualOverride: '本班次由管理员手动调整',
      },
      candidate: {
        weeklyHoursPrefix: '本周',
        hourUnit: '小时',
        continuityBoth: '可与前后时段连续',
        continuityPrevious: '可与上一时段连续',
        continuityNext: '可与下一时段连续',
      },
    },
    
    // Language
    language: '语言',
    switchLanguage: '切换语言',
    chinese: '中文',
    english: 'English',
    
    // Days
    monday: '周一',
    tuesday: '周二',
    wednesday: '周三',
    thursday: '周四',
    friday: '周五',
    
    // Periods
    period1: '第1节',
    period2: '第2节',
    period3: '第3节',
    period4: '第4节',
    period5: '第5节',
    period6: '第6节',
    period7: '第7节',
    period8: '第8节',
  },
  en: {
    // Common
    appName: 'IBC Scheduling System',
    selectUser: 'Select User',
    addUser: 'Add User',
    backToHome: 'Back to Home',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    loading: 'Loading...',
    time: 'Period',
    slots: 'slots',
    
    // Home Page
    welcome: 'Select Your Name',
    welcomeSubtitle: 'Choose your name to start scheduling',
    homeWeeklyScheduleTitle: 'This Week Schedule',
    homeWeeklyScheduleSubtitle: 'Expand to review the current weekly assignments in read-only mode.',
    homeWeeklyScheduleEmpty: 'No schedule has been arranged for this week yet',
    homeWeeklyScheduleExpand: 'Tap to expand this week schedule',
    homeWeeklyScheduleCollapse: 'Tap to collapse this week schedule',
    homeWeeklyScheduleAssignedCount: 'Assigned slots',
    homeWeeklyScheduleParticipants: 'Participants',
    enterName: 'Enter name',
    adminLogin: 'Admin Login',
    
    // Schedule Page
    scheduleTitle: 'Availability',
    scheduleSubtitle: 'Click cells to mark your available time slots',
    selectedSlots: 'Selected slots',
    available: 'Available',
    unavailable: 'Unavailable',
    morning: 'Morning',
    afternoon: 'Afternoon',
    info: 'Click cells to mark your available time slots. Blue indicates selected.',
    
    // Admin
    adminTitle: 'Admin Login',
    adminSubtitle: 'Please enter admin password',
    enterPassword: 'Enter password',
    login: 'Login',
    logout: 'Logout',
    wrongPassword: 'Incorrect password',
    loggedIn: 'Logged in',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    scheduleHistory: 'Schedule History',
    scheduleHistorySubtitle: 'Review the latest five schedule snapshots and reopen details.',
    subsidyRecords: 'Subsidy Records',
    subsidyRecordsSubtitle: 'Manage exported subsidy sheets and reopen, copy, re-export, or continue editing them.',
    subsidyRecordsEmpty: 'No exported subsidy records yet',
    historyRange: 'Range',
    historyParticipants: 'Assistants',
    historyGeneratedAt: 'Generated At',
    historyGenerationMode: 'Mode',
    historyCreatedBy: 'Created By',
    historyViewDetails: 'View Details',
    historyEmpty: 'No schedule history yet',
    historyViewing: 'History Snapshot',
    historyBackToLive: 'Back to Live Schedule',
    autoGenerated: 'Auto',
    manualGenerated: 'Manual',
    
    // Admin Tabs
    scheduleOverview: 'Schedule Overview',
    userManagement: 'User Management',
    
    // Admin Schedule
    viewSchedule: 'View and manage all schedules',
    clearSchedule: 'Clear',
    autoSchedule: 'Auto Schedule',
    exportWord: 'Export Word',
    exportCSV: 'Export CSV',
    exportSubsidy: 'Export Subsidy Sheet',
    periodDay: 'Period / Day',
    unassigned: 'Unassigned',
    totalUsers: 'Total Users',
    scheduledSlots: 'Scheduled Slots',
    totalAvailable: 'Total Available',
    
    // Admin Users
    addNewUser: 'Add New User',
    allUsers: 'All Users',
    noUsers: 'No users yet',
    noPhone: 'Not set',
    editUserProfile: 'Edit User Profile',
    phoneNumber: 'Phone Number',
    studentId: 'Student ID',
    department: 'Department',
    major: 'Major',
    studentType: 'Undergrad / Grad',
    grade: 'Grade',
    enterStudentId: 'Enter student ID',
    enterDepartment: 'Enter department',
    enterMajor: 'Enter major',
    enterStudentType: 'Example: Undergraduate',
    enterGrade: 'Example: 2023',
    subsidyProfileReady: 'Subsidy profile ready',
    subsidyProfileIncomplete: 'Subsidy profile incomplete',
    profileSyncRemoteSaved: 'Subsidy profile saved to cloud.',
    profileSyncLocalOnly: 'Saved locally only. Cloud sync failed, so please retry after the issue is fixed.',
    subsidySchemaWarning: 'The subsidy profile schema is unhealthy, and cloud reads or writes may fail.',
    subsidySchemaBlocked: 'Required subsidy profile fields are missing, so cloud save and subsidy export have been blocked.',
    exportSubsidyTitle: 'Export Subsidy Details',
    exportSubsidySubtitle: 'Export the current natural month without changing the template layout.',
    subsidyDraftActive: 'Active cloud draft',
    subsidyDraftNew: 'New editing session',
    subsidyDraftLoading: 'Loading draft...',
    subsidyDraftLoaded: 'Your latest saved draft has been restored.',
    subsidyDraftLoadFailed: 'Failed to load the draft. A fresh editor was created from the live schedule instead.',
    subsidyDraftSaved: 'Draft saved to cloud.',
    subsidyDraftSaveFailed: 'Failed to save draft. Please try again.',
    subsidyExportArchived: 'Subsidy sheet exported and archived.',
    subsidyExportFailed: 'Failed to export subsidy sheet. Please try again.',
    saveDraft: 'Save Draft',
    exportAndArchive: 'Export & Archive',
    preparerName: 'Preparer Signature',
    preparerPhone: 'Preparer Phone',
    preparedDate: 'Prepared Date',
    naturalMonthRange: 'Range',
    hourlyRate: 'Hourly Rate',
    monthlyHours: 'Monthly Hours',
    systemHours: 'System Hours',
    approvedHours: 'Approved Hours',
    subsidyAmount: 'Amount',
    totalsLabel: 'Totals',
    totalApprovedHours: 'Total Hours',
    totalApprovedAmount: 'Total Amount',
    overLimitNote: 'Note over 711',
    exportNow: 'Export Now',
    missingProfileData: 'These users still need subsidy details:',
    noScheduledUsers: 'No scheduled data to export this month',
    exportListEmpty: 'The export list is empty. Add an assistant or keep at least one row.',
    allowanceReady: 'Ready',
    allowanceNeedsNote: 'Needs note',
    allowanceMissingData: 'Missing data',
    assistantName: 'Assistant',
    addAssistant: 'Add Assistant',
    addAssistantSubtitle: 'Add existing assistants into this export before downloading.',
    searchAssistantPlaceholder: 'Search assistants not already in the list',
    noAssistantsToAdd: 'No assistants available to add',
    confirmRemoveAssistant: 'Remove Assistant',
    confirmRemoveAssistantMessage: 'Remove this assistant from the current export list?',
    subsidyRecordMonth: 'Month',
    subsidyRecordExportedAt: 'Exported At',
    subsidyRecordDetails: 'Subsidy Record Details',
    subsidyRecordContinueEdit: 'Continue Editing',
    subsidyRecordCopy: 'Copy Record',
    subsidyRecordReExport: 'Re-export',
    subsidyRecordDelete: 'Delete Record',
    subsidyRecordCopied: 'A new cloud draft has been created from this record.',
    subsidyRecordReadyToEdit: 'A new draft has been created and is ready to edit.',
    subsidyRecordCloneFailed: 'Failed to copy this record. Please try again.',
    subsidyRecordReExported: 'The subsidy record has been exported again.',
    subsidyRecordDeleted: 'Subsidy record deleted.',
    subsidyRecordDeleteFailed: 'Failed to delete subsidy record. Please try again.',
    subsidyRecordConfirmDelete: 'Delete Subsidy Record',
    subsidyRecordConfirmDeleteMessage: 'Delete this exported subsidy record? This action cannot be undone.',
    subsidySourceSchedule: 'Schedule export',
    subsidySourceRecordCopy: 'Record copy',
    invalidApprovedHours: 'Enter a valid hour value',
    negativeApprovedHours: 'Hours cannot be negative',
    hoursLimitExceeded: 'Hours cannot exceed 30',
    hoursUnitShort: 'h',
    selectAssignee: 'Select Assignee',
    unassign: 'Unassign',
    selected: 'Selected',
    noOneAvailable: 'No one available',
    peopleAvailable: 'available',
    extraDutyPlaceholder: 'Example: extra duty this month',
    autoScheduleSettingsTitle: 'Auto-Schedule Settings',
    autoScheduleSettingsSubtitle: 'Adjust the weekly soft limit and what counts as close hours before running auto-schedule.',
    weeklySoftLimitHours: 'Weekly soft limit (hours)',
    closeHoursThreshold: 'Close-hours threshold (hours)',
    explanationInfo: 'Assignment Explanation',
    assignedResult: 'Assigned To',
    matchedRules: 'Matched Rules',
    candidateList: 'Candidates',
    rejectionReasonTitle: 'Why Others Were Not Chosen',
    noExplanation: 'No explanation is available for this slot yet',
    explanation: {
      badge: {
        singleCandidate: 'Single Lock',
        hoursPriority: 'Hours Priority',
        continuityPriority: 'Continuity Priority',
        stableTiebreak: 'Stable Tiebreak',
        manualAssignment: 'Manual Assignment',
        softLimitWarning: 'Near Limit',
      },
      rule: {
        singleCandidate: 'Single Candidate Lock',
        hoursPriority: 'Lower Weekly Hours Preferred',
        continuityPriority: 'Continuity Preferred',
        stableTiebreak: 'Stable Tiebreak',
        manualAssignment: 'Manual Assignment',
      },
      reason: {
        softLimitReached: 'Already near or over the soft limit',
        higherWeeklyHours: 'Higher weekly hours this week',
        lowerContinuitySameHours: 'Same hours, but weaker continuity',
        lowerContinuityCloseHours: 'Similar hours, but weaker continuity',
        stableTiebreak: 'Lost on the stable tiebreak rule',
      },
      note: {
        softLimitWarning: 'Already near or over the soft limit',
        manualOverride: 'This slot was manually adjusted by an administrator',
      },
      candidate: {
        weeklyHoursPrefix: 'This week',
        hourUnit: 'hours',
        continuityBoth: 'Can connect to both adjacent periods',
        continuityPrevious: 'Can connect to the previous period',
        continuityNext: 'Can connect to the next period',
      },
    },
    
    // Language
    language: 'Language',
    switchLanguage: 'Switch Language',
    chinese: '中文',
    english: 'English',
    
    // Days
    monday: 'Mon',
    tuesday: 'Tue',
    wednesday: 'Wed',
    thursday: 'Thu',
    friday: 'Fri',
    
    // Periods
    period1: 'Period 1',
    period2: 'Period 2',
    period3: 'Period 3',
    period4: 'Period 4',
    period5: 'Period 5',
    period6: 'Period 6',
    period7: 'Period 7',
    period8: 'Period 8',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('ibc-language');
    return saved === 'zh' || saved === 'en' ? saved : 'zh';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('ibc-language', lang);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((prev: Language) => {
      const next = prev === 'zh' ? 'en' : 'zh';
      localStorage.setItem('ibc-language', next);
      return next;
    });
  }, []);

  const t = useCallback((key: string): string => {
    const keys = key.split('.');
    let value: unknown = translations[language];
    
    for (const k of keys) {
      if (typeof value === 'object' && value !== null) {
        value = (value as Record<string, unknown>)[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
